# Generated by Django 3.2.9 on 2022-02-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='AddressBook',
        ),
    ]
